name: agora-uploader

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  releases-matrix:
    name: Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64]
        exclude:  
          # windows/386 and darwin/386 seems useless 
          - goarch: "386"
            goos: windows 
          - goarch: "386"
            goos: darwin     
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: env GOOS=${{matrix.goos}} GOARCH=${{matrix.goarch}} go build ./...
      
    - name: install
      run: env GOOS=${{matrix.goos}} GOARCH=${{matrix.goarch}} go install -v
    
    - name: Set GOBIN env
      run: echo GOBIN=$(go env GOPATH) >> ${GITHUB_ENV} 
          
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        # Artifact name        
        name: agora-uploader-${{ matrix.goos }}
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ env.GOBIN }}/bin/
        if-no-files-found: warn         
